name: Resume NextJs CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            -   uses: actions/checkout@v4

            # Run tests
            -   name: Get project's node version
                run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
                id: nvm

            -   name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
                    cache: 'npm'

            -   run: npm ci
            -   run: npm test

            # Deploy to Vercel
            -   name: Install Vercel CLI
                run: npm install --global vercel@latest
    
            -   name: Build Project Artifacts
                run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --yes

            -   name: Deploy Project Artifacts to Vercel
                run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --yes
